# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 851bfbf8410f5f132fdf8e6a1d26af099c05e0026440d4b389ea822f9821961d27a6a3111cad5260987374ba330f3298524edc059e3da1de2f300416fb297dfe

test:
  secret_key_base: 2e6304961e07ae5e8c82e35a83faaffea36c003d2538b2f7f709fe31f2033811698e167d2b51b89a600484fcd14cb5447c1a0c36f968c851336ce61b51e37745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
